=encoding UTF-8

=head1 NAME

lib::safe - check that none of the dirs in @INC is writable by the current user

=head1 SYNOPSIS

    use lib::safe;

=head1 DESCRIPTION

This is an experimental pragma to somehow provide a better solution
for the CVS-2016-1238 problem.

=head1 AUTHOR

Sébastien Aperghis-Tramoni

